dist: bionic
sudo: false

language: node_js
node_js:
  - 12

cache:
  directories:
    - ./node_modules
install:
  - npm install
script:
  - npm run-script build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  bucket: "meghaduta.org"
  skip_cleanup: true
  acl: public_read
  local_dir: "dist/iotx-angular"
