language: node_js
node_js:
  - 12
install:
  - yarn
script:
  - yarn build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  bucket: "meghaduta.org"
  skip_cleanup: true
  acl: public_read
  local_dir: "dist/iotx-angular"
